# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tumblr-Lab1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tumblr-Lab1
  # This pulls in the latest version of Alamofire >= 4.4 but less than 5.0.
  pod 'Alamofire', '~> 4.4'
  # Add additional dependencies
  pod 'AlamofireImage'
  
  target 'Tumblr-Lab1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Tumblr-Lab1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
